version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./prisma/dev.db:/usr/src/app/prisma/dev.db
    environment:
      - PORT=3000
      - DATABASE_URL=file:./dev.db
